name: CI

on: [push]

env:
  OTP_VERSION: 28.0.1
  ELIXIR_VERSION: 1.19.0-rc.0-otp-28
  NERVES_BOOTSTRAP_VERSION: 1.13.1

permissions:
  id-token: write
  contents: read

jobs:
  get-br-dependencies:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: gridpoint-com/actions-nerves-system@v1
      - name: Get Buildroot Dependencies
        uses: ./.actions/get-br-dependencies
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
          nerves-bootstrap-version: ${{ env.NERVES_BOOTSTRAP_VERSION }}
          push-to-download-site: false
          download-site-url: ${{ vars.PUBLIC_S3_SITE }}
          download-site-bucket-uri: ${{ vars.S3_BUCKET }}
          aws-role: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
  build-system:
    needs: [get-br-dependencies]
    runs-on: ubuntu-22.04
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true
      # needed for the docker nerves build runner
      - run: mkdir -p /home/runner/.ssh
      - uses: actions/checkout@v4
      - uses: gridpoint-com/actions-nerves-system@v1
      - name: Build nerves_system
        uses: ./.actions/build-system
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
          nerves-bootstrap-version: ${{ env.NERVES_BOOTSTRAP_VERSION }}
  deploy-system:
    needs: [build-system]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gridpoint-com/actions-nerves-system@v1
      - name: Deploy nerves_system
        uses: ./.actions/deploy-system
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}